# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f20c3520ae7352a606a1fabb88dca24b9e3b513501e675877175f0cf490a988baa9c79abc81a2bcb7b73d661f9d6b140e09627a7792b754bb4f5911a9a9cdf18

test:
  secret_key_base: 8785eb41246059e7ab77088c8f03d29e71ce768f0be2fef7e5682b178305976efaf41a7ebdd806eacb848c75b8000462dfec488bee01c57972d51e8f6c42d48f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
